# Generated by Django 2.2.6 on 2019-10-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_invoice_purchased_items'),
        ('customer', '0002_auto_20191019_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_ledger', to='sales.Invoice'),
        ),
    ]
