# Generated by Django 2.2.6 on 2019-10-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191010_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='date',
            new_name='dated_order',
        ),
        migrations.AddField(
            model_name='stockin',
            name='buying_price_item',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Buying Price for a Single Item', max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='stockin',
            name='total_buying_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
