# Generated by Django 2.2.6 on 2019-10-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_invoice_purchased_items'),
        ('product', '0005_purchaseditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_purchased', to='sales.Invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockout',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_stockout', to='sales.Invoice'),
        ),
    ]
