# Generated by Django 2.2.6 on 2019-10-22 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191022_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
