# Generated by Django 2.2.6 on 2020-12-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_notify_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='buying_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='stockin',
            name='selling_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
