# Generated by Django 2.2.6 on 2019-10-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='credit_debit_type',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
