# Generated by Django 2.2.6 on 2019-10-24 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerledger_invoice'),
        ('banking_system', '0002_auto_20191023_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bankdetail', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
