# Generated by Django 2.2.6 on 2019-10-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0004_remove_bankdetail_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_branch', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='banking_system.Bank'),
        ),
    ]
