# Generated by Django 2.2.6 on 2019-10-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0005_auto_20191024_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bank_name',
            new_name='name',
        ),
    ]
