# Generated by Django 2.2.6 on 2019-11-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20191111_1436'),
        ('banking_system', '0006_auto_20191024_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='amount',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_invoice', to='sales.Invoice'),
        ),
    ]
