# Generated by Django 2.2.6 on 2019-11-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0006_auto_20191024_1848'),
        ('sales', '0003_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_invoice', to='banking_system.BankDetail'),
        ),
    ]
