# Generated by Django 2.2.6 on 2019-11-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoice_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bank',
        ),
    ]
